spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      connection-test-query: SELECT 1
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      schema: vehicles
  jpa:
    show-sql: true
    properties:
      hibernate.default_schema: ${spring.datasource.hikari.schema}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: ${spring.datasource.hikari.schema}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
